//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 2 colors.
  struct color {
    /// Color `LogoColor`.
    static let logoColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "LogoColor")
    /// Color `NavigationBarColor`.
    static let navigationBarColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "NavigationBarColor")
    
    /// `UIColor(named: "LogoColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func logoColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.logoColor, compatibleWith: traitCollection)
    }
    
    /// `UIColor(named: "NavigationBarColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func navigationBarColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.navigationBarColor, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 2 files.
  struct file {
    /// Resource file `input.xcfilelist`.
    static let inputXcfilelist = Rswift.FileResource(bundle: R.hostingBundle, name: "input", pathExtension: "xcfilelist")
    /// Resource file `output.xcfilelist`.
    static let outputXcfilelist = Rswift.FileResource(bundle: R.hostingBundle, name: "output", pathExtension: "xcfilelist")
    
    /// `bundle.url(forResource: "input", withExtension: "xcfilelist")`
    static func inputXcfilelist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.inputXcfilelist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "output", withExtension: "xcfilelist")`
    static func outputXcfilelist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.outputXcfilelist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 3 images.
  struct image {
    /// Image `LaunchImage`.
    static let launchImage = Rswift.ImageResource(bundle: R.hostingBundle, name: "LaunchImage")
    /// Image `Zomato-flat-logo`.
    static let zomatoFlatLogo = Rswift.ImageResource(bundle: R.hostingBundle, name: "Zomato-flat-logo")
    /// Image `zomato-logo-navigation-bar`.
    static let zomatoLogoNavigationBar = Rswift.ImageResource(bundle: R.hostingBundle, name: "zomato-logo-navigation-bar")
    
    /// `UIImage(named: "LaunchImage", bundle: ..., traitCollection: ...)`
    static func launchImage(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launchImage, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Zomato-flat-logo", bundle: ..., traitCollection: ...)`
    static func zomatoFlatLogo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.zomatoFlatLogo, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "zomato-logo-navigation-bar", bundle: ..., traitCollection: ...)`
    static func zomatoLogoNavigationBar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.zomatoLogoNavigationBar, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    /// Nib `CityTableViewCell`.
    static let cityTableViewCell = _R.nib._CityTableViewCell()
    
    /// `UINib(name: "CityTableViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.cityTableViewCell) instead")
    static func cityTableViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.cityTableViewCell)
    }
    
    static func cityTableViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> CityTableViewCell? {
      return R.nib.cityTableViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? CityTableViewCell
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `CityTableViewCell`.
    static let cityTableViewCell: Rswift.ReuseIdentifier<CityTableViewCell> = Rswift.ReuseIdentifier(identifier: "CityTableViewCell")
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `CitiesStoryboard`.
    static let citiesStoryboard = _R.storyboard.citiesStoryboard()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `RootStoryboard`.
    static let rootStoryboard = _R.storyboard.rootStoryboard()
    
    /// `UIStoryboard(name: "CitiesStoryboard", bundle: ...)`
    static func citiesStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.citiesStoryboard)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "RootStoryboard", bundle: ...)`
    static func rootStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.rootStoryboard)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    struct _CityTableViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = CityTableViewCell
      
      let bundle = R.hostingBundle
      let identifier = "CityTableViewCell"
      let name = "CityTableViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> CityTableViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? CityTableViewCell
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try citiesStoryboard.validate()
      try launchScreen.validate()
      try rootStoryboard.validate()
    }
    
    struct citiesStoryboard: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let citiesViewController = StoryboardViewControllerResource<CitiesViewController>(identifier: "CitiesViewController")
      let name = "CitiesStoryboard"
      
      func citiesViewController(_: Void = ()) -> CitiesViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: citiesViewController)
      }
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "NavigationBarColor", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'NavigationBarColor' is used in storyboard 'CitiesStoryboard', but couldn't be loaded.") }
        }
        if _R.storyboard.citiesStoryboard().citiesViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'citiesViewController' could not be loaded from storyboard 'CitiesStoryboard' as 'CitiesViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if UIKit.UIImage(named: "Zomato-flat-logo", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Zomato-flat-logo' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
          if UIKit.UIColor(named: "LogoColor", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'LogoColor' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        }
      }
      
      fileprivate init() {}
    }
    
    struct rootStoryboard: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = RootNavigationController
      
      let bundle = R.hostingBundle
      let name = "RootStoryboard"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
